### ISSUE TITLE
set_xbot_config issue

### ISSUE THREAD

**Issue by nkashiri** [ADVRHumanoids/XBotControl#12] opened 2019-04-23 09:41 UTC
On setting the config file, I get:
$ set_xbot_config $XBOT_ROOT/configs/CentauroConfig/centauro_basic.yaml
/opt/xbot/build/install/bin/set_xbot_config: line 24: /home/navvab/.xbot/active_config.yaml: No such file or directory
/opt/xbot/build/install/share/xbot/configs/CentauroConfig/centauro_basic.yaml

The problem is the folder ".xbot" does not exist in my home directory.

@liesrock

**Comment by liesrock** [comment] 2019-04-23 10:40
Hi @nkashiri, thanks a lot! Are you sure you are sourcing bash file of the binaries?

**Comment by nkashiri** [comment] 2019-04-23 10:49
I think so, I added 
. /opt/xbot/build/install/share/xbot/setup.bash 
to .bashrc
and then sourced it by
 source ~/.bashrc
and I think it's fine, because I get the address by ecchoing the $XBOT.. 
Should I do something else?

**Comment by liesrock** [comment] 2019-04-23 15:04
You are doing everything good: the issue is related with the setup.bash, it is fixed in:

https://github.com/ADVRHumanoids/XBotControl/releases/tag/v1.1.1

**Comment by liesrock** [comment] 2019-04-23 15:24
Tested.

**Closed by liesrock** 2019-04-23 15:24 UTC
Labels: bug
